apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-guardian

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - ai-service.yaml
  - ingestion-service.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: log-guardian
